environment: dev

vote:
  replicaCount: 1
  service:
    nodePort: 31010

result:
  replicaCount: 1
  service:
    nodePort: 31011

worker:
  replicaCount: 1

db:
  replicaCount: 1

redis:
  replicaCount: 1